#!/usr/bin/env python3

from core.classes.Shell import Shell,Command


if __name__ == '__main__':
    cmds = {
        'exit':Command('exit',lambda : self.shell.stop()),
        'quit':Command('quit',lambda : self.shell.stop()),
        'pymod':Command('pymod',lambda : print(self.shell))
    }
    shell = Shell(cmds)
    shell.loop()